print('Welcome to the tip calculator!')
totalBill = input('What was the total bill? $')
tip = input('How much tip would you like to give? 10, 12, or 15?')
people = input('How many people to split the bill?')
billEachPerson = round(float(totalBill) / float(people), 2)
# print(billEachPerson)
billPlusTipEachPerson = round(billEachPerson * (float(float(tip)/100)), 2)
# print(billEachPerson + billPlusTipEachPerson)
print('Each person should pay: $%.2f' % (billEachPerson + billPlusTipEachPerson))
input()