# print('hello')

# a = input("Bilangan ke 1: ")
# b = input("Bilangan ke 2: ")
# print(int(a) + int(b))
# input()
# print()

print('Welcome to the Band Name Generator', end='\n')
print("what's the name of the city you grew up in?", end='\n')
city_name = input()
print("What's your pet's name?")
pet_name = input()
print('Your band name could be ' + city_name + ' ' + pet_name)
input()